version: 1
disable_existing_loggers: false
formatters:
  detailed:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/application.log
    maxBytes: 104857600
    backupCount: 10
loggers:
  root:
    level: DEBUG
    handlers:
      - file